version: "3.9"
services:
   telegram-bot:
      image: engineeringolympus:latest
      command: sh -c "python bot.py"
   redis:
      image: "redis:alpine"
      command: redis-server --requirepass ${REDIS_PASSWORD}
      ports:
      - "6379:6379"